- name: Install nginx
  become: true
  apt:
    name: nginx
    state: present
    update_cache: yes

- name: Ensure nginx is running
  become: true
  service:
    name: nginx
    state: started
    enabled: yes

- name: Deploy proxy config
  become: true
  template:
    src: proxy_nginx.conf.j2
    dest: /etc/nginx/sites-available/proxy
    owner: root
    group: root
    mode: '0644'

- name: Enable proxy site
  become: true
  file:
    src: /etc/nginx/sites-available/proxy
    dest: /etc/nginx/sites-enabled/proxy
    state: link
    force: yes

- name: Remove default site
  become: true
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Reload nginx
  become: true
  service:
    name: nginx
    state: reloaded
