- name: Set hostname
  hostname:
    name: "{{ inventory_hostname }}"

- name: Install default packages
  become: true
  apt:
    name: "{{ packages_to_install }}"
    state: present
    update_cache: yes
